version: 0.2

phases:
    install:
    runtime-versions:
            nodejs: 10
       commands:
          - npm install
          - npm install -g @angular/cli
          
    build:
        commands:
        # Builds Angular application. You can also build using custom environment here like mock or staging
        - echo Build started on `date`
        - ng build --prod

    post_build:
        commands:
        # Clear S3 bucket.
        - aws s3 rm s3://thepassionwork.com --recursive
        - echo S3 bucket is cleared.
        # Copy dist folder to S3 bucket, As of Angular 6, builds are stored inside an app folder in distribution and not at the root of the dist folder
        - aws s3 cp dist/MovieFrontEndDemo/ s3://thepassionwork.com  --recursive
        - echo Build completed on `date`
# artifacts:
#    files:
#       - dist/**/*
