version: 0.2
phases:
  install:
    runtime-versions:
       nodejs: 10
    commands:
       - npm install
       - npm install -g @angular/cli
  build:
    commands:
       - ng build --prod
  post_build:
    commands:
       - aws s3 rm s3://thepassionwork.com --recursive
       - aws s3 cp dist/MovieFrontEndDemo/ s3://thepassionwork.com --recursive
