version: 0.2

env:
    variables:
        S3_BUCKET: "thepassionwork.com"
APP_NAME: "MovieFrontEndDemo"
BUILD_ENV : "prod"

phases:
    install:
        commands:
          - npm install
          - npm install -g @angular/cli

build:
        commands:
        # Builds Angular application. You can also build using custom environment here like mock or staging
        - echo Build started on `date`
        - ng build --${BUILD_ENV}

post_build:
        commands:
        # Clear S3 bucket.
        - aws s3 rm s3://${S3_BUCKET} --recursive
        - echo S3 bucket is cleared.
        # Copy dist folder to S3 bucket, As of Angular 6, builds are stored inside an app folder in distribution and not at the root of the dist folder
        - aws s3 cp dist/${APP_NAME}/ s3://${S3_BUCKET} --recursive
        - echo Build completed on `date`

